export enum AppErrorCodes{
    ERR_CODE_SYSTEM_ERR = 'ERP-1000',
    NOT_LOGGED_IN = 'ERP-1001',
    INVALID_SECURITY_TOKEN = 'ERP-1002',
    ENTITY_NOT_FOUND = 'ERP-1003',
    ENTITY_EXISTS = 'ERP-1004',
    ENTITY_VALIDATION_ERR = 'ERP-1005',
    BAD_REQUEST = 'ERP-1006',
    CUSTOM_ERROR_CODE = 'Error-Code',
}